name: Hello-World
on: push
jobs:
  HelloWorld-job:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actiona/checkout@v3
     - name: use node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18.x'
     - run: npminstall
     - run: npm run build
     
