name: Hello-World
on: push
jobs:
  HelloWorld-Job:
    runs-on: ubuntu-latest
    steps:
     - name: Check out repository code
       uses: actions/checkout@v3
     - run: echo "$(cat hello_world.txt)"
